### ISSUE TITLE
Fill out form by user

### ISSUE THREAD

**Issue by MarvinKlein1508** [MarvinKlein1508/FormularPortal#2]
This issue is to track the progression in filling out forms by the user

- [x] Validate require login forms
- [x] Implement file uploads
- [x] Save form
- [x] #13
- [x] Fix invisible validation message for FormElements which are part of a `FormTableElement`
